/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WofRouteImport } from './routes/wof'
import { Route as RpsRouteImport } from './routes/rps'
import { Route as PixelArtRouteImport } from './routes/pixel-art'
import { Route as NumberGuessingRouteImport } from './routes/number-guessing'
import { Route as DiceRollerRouteImport } from './routes/dice-roller'
import { Route as CoinFlipRouteImport } from './routes/coin-flip'
import { Route as IndexRouteImport } from './routes/index'

const WofRoute = WofRouteImport.update({
  id: '/wof',
  path: '/wof',
  getParentRoute: () => rootRouteImport,
} as any)
const RpsRoute = RpsRouteImport.update({
  id: '/rps',
  path: '/rps',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelArtRoute = PixelArtRouteImport.update({
  id: '/pixel-art',
  path: '/pixel-art',
  getParentRoute: () => rootRouteImport,
} as any)
const NumberGuessingRoute = NumberGuessingRouteImport.update({
  id: '/number-guessing',
  path: '/number-guessing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceRollerRoute = DiceRollerRouteImport.update({
  id: '/dice-roller',
  path: '/dice-roller',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinFlipRoute = CoinFlipRouteImport.update({
  id: '/coin-flip',
  path: '/coin-flip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coin-flip': typeof CoinFlipRoute
  '/dice-roller': typeof DiceRollerRoute
  '/number-guessing': typeof NumberGuessingRoute
  '/pixel-art': typeof PixelArtRoute
  '/rps': typeof RpsRoute
  '/wof': typeof WofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coin-flip': typeof CoinFlipRoute
  '/dice-roller': typeof DiceRollerRoute
  '/number-guessing': typeof NumberGuessingRoute
  '/pixel-art': typeof PixelArtRoute
  '/rps': typeof RpsRoute
  '/wof': typeof WofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coin-flip': typeof CoinFlipRoute
  '/dice-roller': typeof DiceRollerRoute
  '/number-guessing': typeof NumberGuessingRoute
  '/pixel-art': typeof PixelArtRoute
  '/rps': typeof RpsRoute
  '/wof': typeof WofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coin-flip'
    | '/dice-roller'
    | '/number-guessing'
    | '/pixel-art'
    | '/rps'
    | '/wof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coin-flip'
    | '/dice-roller'
    | '/number-guessing'
    | '/pixel-art'
    | '/rps'
    | '/wof'
  id:
    | '__root__'
    | '/'
    | '/coin-flip'
    | '/dice-roller'
    | '/number-guessing'
    | '/pixel-art'
    | '/rps'
    | '/wof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoinFlipRoute: typeof CoinFlipRoute
  DiceRollerRoute: typeof DiceRollerRoute
  NumberGuessingRoute: typeof NumberGuessingRoute
  PixelArtRoute: typeof PixelArtRoute
  RpsRoute: typeof RpsRoute
  WofRoute: typeof WofRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wof': {
      id: '/wof'
      path: '/wof'
      fullPath: '/wof'
      preLoaderRoute: typeof WofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rps': {
      id: '/rps'
      path: '/rps'
      fullPath: '/rps'
      preLoaderRoute: typeof RpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-art': {
      id: '/pixel-art'
      path: '/pixel-art'
      fullPath: '/pixel-art'
      preLoaderRoute: typeof PixelArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/number-guessing': {
      id: '/number-guessing'
      path: '/number-guessing'
      fullPath: '/number-guessing'
      preLoaderRoute: typeof NumberGuessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice-roller': {
      id: '/dice-roller'
      path: '/dice-roller'
      fullPath: '/dice-roller'
      preLoaderRoute: typeof DiceRollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin-flip': {
      id: '/coin-flip'
      path: '/coin-flip'
      fullPath: '/coin-flip'
      preLoaderRoute: typeof CoinFlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoinFlipRoute: CoinFlipRoute,
  DiceRollerRoute: DiceRollerRoute,
  NumberGuessingRoute: NumberGuessingRoute,
  PixelArtRoute: PixelArtRoute,
  RpsRoute: RpsRoute,
  WofRoute: WofRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
